### ISSUE TITLE
Regarding infermedica-api project

### ISSUE THREAD

**Issue by sowmya-indukuri** [jesseokeya/infermedica#3]
Hi,
Your project seemed interesting to me, but I am bit confused on how to run this code and how the output looks like? Is it a full-stack project? if so, where can I find front-end code? @jesseokeya 

Thanks, in advance

**Comment by jesseokeya** [comment]
Hey Sowmya, Sorry i missed the question erlier. Yh so basically the library is a wrapper of the infermedica rest api. There is no client or frontend per say. If someone is using the api it would make sense to integrate it to a backend codebase. @sowmya-indukuri

**Comment by sowmya-indukuri** [comment]
Yeah I figured about it later! Thanks for your reply!
